import { KnowledgeContextItem } from '../chat.types';
import { PROFESSIONAL_PROFILE } from './professional-profile';

export const PROFILE_KNOWLEDGE_ITEMS: readonly KnowledgeContextItem[] = [
  {
    sourceType: 'profile',
    sourceId: 'main-profile',
    title: 'Perfil profesional',
    text: [
      PROFESSIONAL_PROFILE.introduction,
      'Se mueve con comodidad entre frontend, backend, cloud y arquitectura.',
      'El portfolio busca mostrar experiencia real construyendo productos, tomando decisiones técnicas con criterio y armando soluciones que se puedan mantener.',
    ].join(' '),
    tags: [
      'profile',
      'fullstack',
      'backend',
      'cloud',
      'portfolio',
      'matias-galeano',
    ],
  },
  {
    sourceType: 'profile',
    sourceId: 'main-stack',
    title: 'Stack principal',
    text: [
      PROFESSIONAL_PROFILE.stack,
      PROFESSIONAL_PROFILE.currentStack,
      PROFESSIONAL_PROFILE.tooling,
    ].join(' '),
    tags: [
      'skills',
      'typescript',
      'angular',
      'ionic',
      'nestjs',
      'mongodb',
      'postgresql',
      'aws',
      'lambda',
      'ec2',
      'ecs',
      'ecr',
      's3',
      'cloudfront',
      'cloudwatch',
      'r2',
      'docker',
      'github-actions',
    ],
  },
  {
    sourceType: 'profile',
    sourceId: 'main-experience',
    title: 'Experiencia laboral',
    text: [
      PROFESSIONAL_PROFILE.currentWork,
      PROFESSIONAL_PROFILE.currentStack,
      PROFESSIONAL_PROFILE.career,
    ].join(' '),
    tags: [
      'experience',
      'ingertec',
      'boreal-it',
      'banco-comafi',
      'fullstack',
      'backend',
      'product',
      'fintech',
    ],
  },
  {
    sourceType: 'profile',
    sourceId: 'main-databases',
    title: 'Experiencia con bases de datos',
    text: PROFESSIONAL_PROFILE.databases,
    tags: [
      'sql server',
      'mssql',
      'postgresql',
      'postgres',
      'rds',
      'aurora',
      'dynamodb',
      'mysql',
      'mongodb',
      'bases de datos',
    ],
  },
  {
    sourceType: 'profile',
    sourceId: 'main-aws',
    title: 'Experiencia profesional con AWS',
    text: PROFESSIONAL_PROFILE.aws,
    tags: [
      'aws',
      'lambda',
      'sqs',
      'colas',
      'cdk',
      'dynamodb',
      'rds',
      'aurora',
      'infraestructura como codigo',
    ],
  },
  {
    sourceType: 'profile',
    sourceId: 'main-strengths',
    title: 'Fortalezas profesionales',
    text: [
      'Se enfoca en soluciones simples, mantenibles y listas para producción.',
      'Suele ordenar bien las responsabilidades entre frontend, backend, cloud y contenido.',
      'Prioriza decisiones técnicas claras, despliegues reproducibles y la complejidad justa para cada problema.',
    ].join(' '),
    tags: [
      'strengths',
      'architecture',
      'maintainability',
      'production',
      'cloud',
      'devops',
    ],
  },
  {
    sourceType: 'profile',
    sourceId: 'main-career-preferences',
    title: 'Idiomas y preferencias profesionales',
    text: [
      PROFESSIONAL_PROFILE.languages,
      PROFESSIONAL_PROFILE.opportunities,
    ].join(' '),
    tags: ['idiomas', 'ingles', 'english', 'propuestas', 'remoto', 'freelance'],
  },
  {
    sourceType: 'profile',
    sourceId: 'main-contact',
    title: 'Contacto profesional',
    text: [
      'El contacto principal se realiza desde el formulario del portfolio en matiasgaleano.dev.',
      'También mantiene presencia pública en GitHub y LinkedIn.',
    ].join(' '),
    tags: ['contact', 'portfolio', 'github', 'linkedin'],
    links: [
      { label: 'Portfolio', url: 'https://matiasgaleano.dev' },
      { label: 'GitHub', url: 'https://github.com/matigaleanodev' },
      {
        label: 'LinkedIn',
        url: 'https://www.linkedin.com/in/matias-galeano-dev',
      },
    ],
  },
];
