import { KnowledgeContextItem } from '../chat.types';

export const PROFILE_KNOWLEDGE_ITEMS: readonly KnowledgeContextItem[] = [
  {
    sourceType: 'profile',
    sourceId: 'main-profile',
    title: 'Perfil profesional',
    text: [
      'Matías Galeano es Fullstack Product Developer de Posadas, Misiones, Argentina.',
      'Se mueve con comodidad entre frontend, backend, cloud y arquitectura.',
      'El portfolio busca mostrar experiencia real construyendo productos, tomando decisiones técnicas con criterio y armando soluciones que se puedan mantener.',
    ].join(' '),
    tags: [
      'profile',
      'fullstack',
      'backend',
      'cloud',
      'portfolio',
      'matias-galeano',
    ],
  },
  {
    sourceType: 'profile',
    sourceId: 'main-stack',
    title: 'Stack principal',
    text: [
      'Stack principal: TypeScript, Angular, Ionic, Node.js y NestJS.',
      'Actualmente trabaja con Angular en frontend y un backend híbrido entre monolito NestJS y microservicios con AWS Lambda.',
      'Trabaja con PostgreSQL en su rol actual y usa con frecuencia Docker, GitHub Actions, AWS Lambda, EC2, ECS, ECR, S3, CloudFront, CloudWatch y Cloudflare R2.',
    ].join(' '),
    tags: [
      'skills',
      'typescript',
      'angular',
      'ionic',
      'nestjs',
      'mongodb',
      'postgresql',
      'aws',
      'lambda',
      'ec2',
      'ecs',
      'ecr',
      's3',
      'cloudfront',
      'cloudwatch',
      'r2',
      'docker',
      'github-actions',
    ],
  },
  {
    sourceType: 'profile',
    sourceId: 'main-experience',
    title: 'Experiencia laboral',
    text: [
      'Trabajó en Ingertec Argentina hasta abril de 2026 como Fullstack Developer y desde entonces trabaja en Boreal IT para Banco Comafi.',
      'En su etapa actual participa en un producto de Fondos Comunes de Inversión con Angular en frontend, backend híbrido entre monolito NestJS y microservicios AWS Lambda, y PostgreSQL como base de datos.',
      'Acumula cerca de cuatro años de experiencia trabajando con software en producción.',
    ].join(' '),
    tags: [
      'experience',
      'ingertec',
      'boreal-it',
      'banco-comafi',
      'fullstack',
      'backend',
      'product',
      'fintech',
    ],
  },
  {
    sourceType: 'profile',
    sourceId: 'main-strengths',
    title: 'Fortalezas profesionales',
    text: [
      'Se enfoca en soluciones simples, mantenibles y listas para producción.',
      'Suele ordenar bien las responsabilidades entre frontend, backend, cloud y contenido.',
      'Prioriza decisiones técnicas claras, despliegues reproducibles y la complejidad justa para cada problema.',
    ].join(' '),
    tags: [
      'strengths',
      'architecture',
      'maintainability',
      'production',
      'cloud',
      'devops',
    ],
  },
  {
    sourceType: 'profile',
    sourceId: 'main-contact',
    title: 'Contacto profesional',
    text: [
      'El contacto principal se realiza desde el formulario del portfolio en matiasgaleano.dev.',
      'También mantiene presencia pública en GitHub y LinkedIn.',
    ].join(' '),
    tags: ['contact', 'portfolio', 'github', 'linkedin'],
    links: [
      { label: 'Portfolio', url: 'https://matiasgaleano.dev' },
      { label: 'GitHub', url: 'https://github.com/matigaleanodev' },
      {
        label: 'LinkedIn',
        url: 'https://www.linkedin.com/in/matias-galeano-dev',
      },
    ],
  },
];
